/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbol_principal;

import arbol_funciones.funciones_archivos;
import arbol_funciones.funciones_recorrido;
import arbol_modelo.Nodo;
import arbol_modelo.Arbol;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author gadia
 */
public class Recorrido extends javax.swing.JFrame {

    /**
     * Creates new form Recorrido
     */
    funciones_recorrido funRec;  
   
    Arbol nArbol;

    public Recorrido() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    //ejecuta el metodo cargarArray de funciones de recorridos
    public void cargar() {
        funRec = new funciones_recorrido();
        nArbol = new Arbol();
       //carga los JtextField
        funRec.cargarArray(nArbol,JT1, JT10, JT11, JT12, JT13, JT14, JT15, JT16, JT17, JT18, JT19, JT2, JT20, JT21, JT22, JT23, JT24, JT25, JT26, JT27, JT28, JT29, JT3, JT30, JT31, JT4, JT5, JT6, JT7, JT8, JT9);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTPanel = new javax.swing.JPanel();
        JT1 = new javax.swing.JTextField();
        JT2 = new javax.swing.JTextField();
        JT3 = new javax.swing.JTextField();
        JT4 = new javax.swing.JTextField();
        JT5 = new javax.swing.JTextField();
        JT6 = new javax.swing.JTextField();
        JT7 = new javax.swing.JTextField();
        JT8 = new javax.swing.JTextField();
        JT9 = new javax.swing.JTextField();
        JT10 = new javax.swing.JTextField();
        JT11 = new javax.swing.JTextField();
        JT12 = new javax.swing.JTextField();
        JT13 = new javax.swing.JTextField();
        JT14 = new javax.swing.JTextField();
        JT15 = new javax.swing.JTextField();
        JT16 = new javax.swing.JTextField();
        JT17 = new javax.swing.JTextField();
        JT18 = new javax.swing.JTextField();
        JT19 = new javax.swing.JTextField();
        JT20 = new javax.swing.JTextField();
        JT21 = new javax.swing.JTextField();
        JT22 = new javax.swing.JTextField();
        JT23 = new javax.swing.JTextField();
        JT24 = new javax.swing.JTextField();
        JT25 = new javax.swing.JTextField();
        JT26 = new javax.swing.JTextField();
        JT27 = new javax.swing.JTextField();
        JT28 = new javax.swing.JTextField();
        JT29 = new javax.swing.JTextField();
        JT30 = new javax.swing.JTextField();
        JT31 = new javax.swing.JTextField();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        JTPanel.setBackground(new java.awt.Color(255, 255, 255));
        JTPanel.setPreferredSize(new java.awt.Dimension(1400, 600));

        JT1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT1.setBorder(null);
        JT1.setHighlighter(null);
        JT1.setPreferredSize(new java.awt.Dimension(30, 30));
        JT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT1ActionPerformed(evt);
            }
        });

        JT2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT2.setBorder(null);
        JT2.setHighlighter(null);
        JT2.setPreferredSize(new java.awt.Dimension(30, 30));
        JT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT2ActionPerformed(evt);
            }
        });

        JT3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT3.setBorder(null);
        JT3.setHighlighter(null);
        JT3.setPreferredSize(new java.awt.Dimension(30, 30));
        JT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT3ActionPerformed(evt);
            }
        });

        JT4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT4.setBorder(null);
        JT4.setHighlighter(null);
        JT4.setPreferredSize(new java.awt.Dimension(30, 30));
        JT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT4ActionPerformed(evt);
            }
        });

        JT5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT5.setBorder(null);
        JT5.setHighlighter(null);
        JT5.setPreferredSize(new java.awt.Dimension(30, 30));
        JT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT5ActionPerformed(evt);
            }
        });

        JT6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT6.setBorder(null);
        JT6.setHighlighter(null);
        JT6.setPreferredSize(new java.awt.Dimension(30, 30));
        JT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT6ActionPerformed(evt);
            }
        });

        JT7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT7.setBorder(null);
        JT7.setHighlighter(null);
        JT7.setPreferredSize(new java.awt.Dimension(30, 30));
        JT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT7ActionPerformed(evt);
            }
        });

        JT8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT8.setBorder(null);
        JT8.setHighlighter(null);
        JT8.setPreferredSize(new java.awt.Dimension(30, 30));
        JT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT8ActionPerformed(evt);
            }
        });

        JT9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT9.setBorder(null);
        JT9.setHighlighter(null);
        JT9.setPreferredSize(new java.awt.Dimension(30, 30));
        JT9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT9ActionPerformed(evt);
            }
        });

        JT10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT10.setBorder(null);
        JT10.setHighlighter(null);
        JT10.setPreferredSize(new java.awt.Dimension(30, 30));
        JT10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT10ActionPerformed(evt);
            }
        });

        JT11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT11.setBorder(null);
        JT11.setHighlighter(null);
        JT11.setPreferredSize(new java.awt.Dimension(30, 30));
        JT11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT11ActionPerformed(evt);
            }
        });

        JT12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT12.setBorder(null);
        JT12.setHighlighter(null);
        JT12.setPreferredSize(new java.awt.Dimension(30, 30));
        JT12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT12ActionPerformed(evt);
            }
        });

        JT13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT13.setBorder(null);
        JT13.setHighlighter(null);
        JT13.setPreferredSize(new java.awt.Dimension(30, 30));
        JT13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT13ActionPerformed(evt);
            }
        });

        JT14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT14.setBorder(null);
        JT14.setHighlighter(null);
        JT14.setPreferredSize(new java.awt.Dimension(30, 30));
        JT14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT14ActionPerformed(evt);
            }
        });

        JT15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT15.setBorder(null);
        JT15.setHighlighter(null);
        JT15.setPreferredSize(new java.awt.Dimension(30, 30));
        JT15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT15ActionPerformed(evt);
            }
        });

        JT16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT16.setBorder(null);
        JT16.setHighlighter(null);
        JT16.setPreferredSize(new java.awt.Dimension(30, 30));
        JT16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT16ActionPerformed(evt);
            }
        });

        JT17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT17.setBorder(null);
        JT17.setHighlighter(null);
        JT17.setPreferredSize(new java.awt.Dimension(30, 30));
        JT17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT17ActionPerformed(evt);
            }
        });

        JT18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT18.setBorder(null);
        JT18.setHighlighter(null);
        JT18.setPreferredSize(new java.awt.Dimension(30, 30));
        JT18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT18ActionPerformed(evt);
            }
        });

        JT19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT19.setBorder(null);
        JT19.setHighlighter(null);
        JT19.setPreferredSize(new java.awt.Dimension(30, 30));
        JT19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT19ActionPerformed(evt);
            }
        });

        JT20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT20.setBorder(null);
        JT20.setHighlighter(null);
        JT20.setPreferredSize(new java.awt.Dimension(30, 30));
        JT20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT20ActionPerformed(evt);
            }
        });

        JT21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT21.setBorder(null);
        JT21.setHighlighter(null);
        JT21.setPreferredSize(new java.awt.Dimension(30, 30));
        JT21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT21ActionPerformed(evt);
            }
        });

        JT22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT22.setBorder(null);
        JT22.setHighlighter(null);
        JT22.setPreferredSize(new java.awt.Dimension(30, 30));
        JT22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT22ActionPerformed(evt);
            }
        });

        JT23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT23.setBorder(null);
        JT23.setHighlighter(null);
        JT23.setPreferredSize(new java.awt.Dimension(30, 30));
        JT23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT23ActionPerformed(evt);
            }
        });

        JT24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT24.setBorder(null);
        JT24.setHighlighter(null);
        JT24.setPreferredSize(new java.awt.Dimension(30, 30));
        JT24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT24ActionPerformed(evt);
            }
        });

        JT25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT25.setBorder(null);
        JT25.setHighlighter(null);
        JT25.setPreferredSize(new java.awt.Dimension(30, 30));
        JT25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT25ActionPerformed(evt);
            }
        });

        JT26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT26.setBorder(null);
        JT26.setHighlighter(null);
        JT26.setPreferredSize(new java.awt.Dimension(30, 30));
        JT26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT26ActionPerformed(evt);
            }
        });

        JT27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT27.setBorder(null);
        JT27.setHighlighter(null);
        JT27.setPreferredSize(new java.awt.Dimension(30, 30));
        JT27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT27ActionPerformed(evt);
            }
        });

        JT28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT28.setBorder(null);
        JT28.setHighlighter(null);
        JT28.setPreferredSize(new java.awt.Dimension(30, 30));
        JT28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT28ActionPerformed(evt);
            }
        });

        JT29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT29.setBorder(null);
        JT29.setHighlighter(null);
        JT29.setPreferredSize(new java.awt.Dimension(30, 30));
        JT29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT29ActionPerformed(evt);
            }
        });

        JT30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT30.setBorder(null);
        JT30.setHighlighter(null);
        JT30.setPreferredSize(new java.awt.Dimension(30, 30));
        JT30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT30ActionPerformed(evt);
            }
        });

        JT31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JT31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JT31.setBorder(null);
        JT31.setHighlighter(null);
        JT31.setPreferredSize(new java.awt.Dimension(30, 30));
        JT31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT31ActionPerformed(evt);
            }
        });

        jB3.setText("Pri Order");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jB4.setText("In Order");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jB5.setText("Post Order");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JTPanelLayout = new javax.swing.GroupLayout(JTPanel);
        JTPanel.setLayout(JTPanelLayout);
        JTPanelLayout.setHorizontalGroup(
            JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTPanelLayout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(412, 412, 412))
            .addGroup(JTPanelLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(JT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265)
                .addComponent(JT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265)
                .addComponent(JT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
            .addGroup(JTPanelLayout.createSequentialGroup()
                .addGroup(JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JTPanelLayout.createSequentialGroup()
                        .addGap(656, 656, 656)
                        .addComponent(JT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JTPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB4)
                        .addGap(18, 18, 18)
                        .addComponent(jB5))
                    .addGroup(JTPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(JT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(JT17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(JT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(JT19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(JT20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(JT21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(JT22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(JT23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(JT24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(JT25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(JT26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(JT27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(JT28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(JT29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(JT30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(JT31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JTPanelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(JT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(JT9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(JT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(JT11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(JT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(JT13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(JT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(JT15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        JTPanelLayout.setVerticalGroup(
            JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(JT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JT24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JT20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JT17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(JTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB3)
                    .addComponent(jB4)
                    .addComponent(jB5))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT1ActionPerformed

    private void JT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT2ActionPerformed

    private void JT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT3ActionPerformed

    private void JT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT8ActionPerformed

    private void JT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT5ActionPerformed

    private void JT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT6ActionPerformed

    private void JT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT7ActionPerformed

    private void JT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT4ActionPerformed

    private void JT9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT9ActionPerformed

    private void JT11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT11ActionPerformed

    private void JT10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT10ActionPerformed

    private void JT15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT15ActionPerformed

    private void JT14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT14ActionPerformed

    private void JT12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT12ActionPerformed

    private void JT13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT13ActionPerformed

    private void JT16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT16ActionPerformed

    private void JT17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT17ActionPerformed

    private void JT19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT19ActionPerformed

    private void JT18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT18ActionPerformed

    private void JT22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT22ActionPerformed

    private void JT23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT23ActionPerformed

    private void JT20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT20ActionPerformed

    private void JT21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT21ActionPerformed

    private void JT28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT28ActionPerformed

    private void JT29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT29ActionPerformed

    private void JT30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT30ActionPerformed

    private void JT31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT31ActionPerformed

    private void JT24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT24ActionPerformed

    private void JT25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT25ActionPerformed

    private void JT26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT26ActionPerformed

    private void JT27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT27ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        //boton pre Order
        funRec = new funciones_recorrido();
        nArbol = new Arbol();
        cargar();
        funRec.ejecPreOrder(nArbol);
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // boton in Order
        funRec = new funciones_recorrido();
        nArbol = new Arbol();
        cargar();
        funRec.ejecInOrder(nArbol);
        
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        // boton Post Order
        funRec = new funciones_recorrido();
        nArbol = new Arbol();
        cargar();
        funRec.ejecPostOrder(nArbol);
        
    }//GEN-LAST:event_jB5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recorrido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recorrido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recorrido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recorrido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recorrido().setVisible(true);
            }
        });
    }

    public void paint(Graphics g) {
        if (g instanceof Graphics2D) {
            Graphics2D g2 = (Graphics2D) g;
            g2.setStroke(new BasicStroke(5.0f));

            super.paint(g);

            g.setColor(Color.BLUE);
            g.drawOval(662, 100, 50, 50);
            g.drawLine(662, 125, 387, 200);
            g.drawLine(712, 125, 987, 200);

            g.drawOval(362, 200, 50, 50);
            g.drawLine(362, 225, 237, 300);
            g.drawLine(412, 225, 537, 300);
            g.drawOval(962, 200, 50, 50);
            g.drawLine(962, 225, 837, 300);
            g.drawLine(1012, 225, 1137, 300);

            g.drawOval(212, 300, 50, 50);
            g.drawLine(212, 325, 163, 400);
            g.drawLine(262, 325, 312, 400);
            g.drawOval(512, 300, 50, 50);
            g.drawLine(512, 325, 462, 400);
            g.drawLine(562, 325, 612, 400);
            g.drawOval(812, 300, 50, 50);
            g.drawLine(812, 325, 762, 400);
            g.drawLine(862, 325, 912, 400);
            g.drawOval(1112, 300, 50, 50);
            g.drawLine(1112, 325, 1062, 400);
            g.drawLine(1162, 325, 1212, 400);

            g.drawOval(138, 400, 50, 50);
            g.drawLine(138, 425, 125, 500);
            g.drawLine(188, 425, 200, 500);
            g.drawOval(287, 400, 50, 50);
            g.drawLine(287, 425, 275, 500);
            g.drawLine(337, 425, 350, 500);
            g.drawOval(437, 400, 50, 50);
            g.drawLine(437, 425, 425, 500);
            g.drawLine(487, 425, 500, 500);
            g.drawOval(587, 400, 50, 50);
            g.drawLine(587, 425, 575, 500);
            g.drawLine(637, 425, 650, 500);
            g.drawOval(737, 400, 50, 50);
            g.drawLine(737, 425, 725, 500);
            g.drawLine(787, 425, 800, 500);
            g.drawOval(887, 400, 50, 50);
            g.drawLine(887, 425, 875, 500);
            g.drawLine(937, 425, 950, 500);
            g.drawOval(1037, 400, 50, 50);
            g.drawLine(1037, 425, 1025, 500);
            g.drawLine(1087, 425, 1100, 500);
            g.drawOval(1187, 400, 50, 50);
            g.drawLine(1187, 425, 1175, 500);
            g.drawLine(1237, 425, 1250, 500);

            g.drawOval(100, 500, 50, 50);
            g.drawOval(175, 500, 50, 50);
            g.drawOval(250, 500, 50, 50);
            g.drawOval(325, 500, 50, 50);
            g.drawOval(400, 500, 50, 50);
            g.drawOval(475, 500, 50, 50);
            g.drawOval(550, 500, 50, 50);
            g.drawOval(625, 500, 50, 50);
            g.drawOval(700, 500, 50, 50);
            g.drawOval(775, 500, 50, 50);
            g.drawOval(850, 500, 50, 50);
            g.drawOval(925, 500, 50, 50);
            g.drawOval(1000, 500, 50, 50);
            g.drawOval(1075, 500, 50, 50);
            g.drawOval(1150, 500, 50, 50);
            g.drawOval(1225, 500, 50, 50);
        }
    }

    /*
       comprueba los valor Jtext  para saber si
    son vacio y sino le agrega -1
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT1;
    private javax.swing.JTextField JT10;
    private javax.swing.JTextField JT11;
    private javax.swing.JTextField JT12;
    private javax.swing.JTextField JT13;
    private javax.swing.JTextField JT14;
    private javax.swing.JTextField JT15;
    private javax.swing.JTextField JT16;
    private javax.swing.JTextField JT17;
    private javax.swing.JTextField JT18;
    private javax.swing.JTextField JT19;
    private javax.swing.JTextField JT2;
    private javax.swing.JTextField JT20;
    private javax.swing.JTextField JT21;
    private javax.swing.JTextField JT22;
    private javax.swing.JTextField JT23;
    private javax.swing.JTextField JT24;
    private javax.swing.JTextField JT25;
    private javax.swing.JTextField JT26;
    private javax.swing.JTextField JT27;
    private javax.swing.JTextField JT28;
    private javax.swing.JTextField JT29;
    private javax.swing.JTextField JT3;
    private javax.swing.JTextField JT30;
    private javax.swing.JTextField JT31;
    private javax.swing.JTextField JT4;
    private javax.swing.JTextField JT5;
    private javax.swing.JTextField JT6;
    private javax.swing.JTextField JT7;
    private javax.swing.JTextField JT8;
    private javax.swing.JTextField JT9;
    private javax.swing.JPanel JTPanel;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    // End of variables declaration//GEN-END:variables
}
